
[life360]
username = "user@email.com"    # Life360 login.
password = "strong password"   # Life360 password.
circle_ids = []                # Optional. List of circles to process. If not specified, app will query the list of circles
# Shouldn't need to change the below entries
auth_token = "cFJFcXVnYWJSZXRyZTRFc3RldGhlcnVmcmVQdW1hbUV4dWNyRUh1YzptM2ZydXBSZXRSZXN3ZXJFQ2hBUHJFOTZxYWtFZHI0Vg"
base_url = "https://api.life360.com/v3/"
token_url = "oauth2/token.json"
circles_url = "circles.json"
circle_url = "circles/"

# Create org, bucket & token by navigating to your influx url from a browser
[influx]
url = "http://localhost:8086"  # Location of influxdb v2 server
bucket = "Life360"             # Name of available bucket
token = "super-secret-token"   # Token with write permission to bucket
org = "your org in influx"     # Org of the bucket
measurement = "location"       # Name to give to measurements

[main]
logverbosity = "INFO" # By increasing level of verbosity = FATAL, ERROR, WARNING, INFO, DEBUG.
loop_seconds = 180    # Time to wait between two queries to Life360's backend. 0 to only query once

